services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.96.0
    container_name: victoriametrics
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=90d"
      - "--httpListenAddr=:8428"
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics-data:/storage
    networks:
      - monitoring-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8428/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
